AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  nestjs

  Sample SAM Template for nestjs

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  NestjsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: nestjs/
      Handler: dist/lambda.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        Nestjs:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: ANY

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  NestjsApi:
    Description: "API Gateway endpoint URL for Prod stage for Nestjs function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  NestjsFunction:
    Description: "Nestjs Lambda Function ARN"
    Value: !GetAtt NestjsFunction.Arn
  NestjsFunctionIamRole:
    Description: "Implicit IAM Role created for Nestjs function"
    Value: !GetAtt NestjsFunctionRole.Arn
